In [3]:
print('Hello')

Hello


In [4]:
#numpy
list1 = [1,2,3,4]
print(list1)
list2 = [5,6]
print(list2)

[1, 2, 3, 4]
[5, 6]


In [5]:
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [6]:
list2 = [5,6,7,8]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [7]:
print(list1+2)

TypeError: can only concatenate list (not "int") to list

In [8]:
import numpy as np
l1 = np.array(list1)
print(l1)

[1 2 3 4]


In [9]:
print(l1+2)

[3 4 5 6]


In [10]:
print((l1+3)/10)

[0.4 0.5 0.6 0.7]


In [11]:
l2 = np.array(list2)
print(l1+l2)

[ 6  8 10 12]


In [13]:
for l in l1:
    print(l)

1
2
3
4


In [14]:
#Pandas
import pandas as pd

In [15]:
df = pd.Series([1,2,3,4,5,6])
df

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [16]:
df.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
df.tail()

1    2
2    3
3    4
4    5
5    6
dtype: int64

In [18]:
df.shape

(6,)

In [19]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 6 entries, 0 to 5
Series name: None
Non-Null Count  Dtype
--------------  -----
6 non-null      int64
dtypes: int64(1)
memory usage: 176.0 bytes


In [20]:
d1 = {'s1':10, 's2':20,'s3':30}
d2 = {'s1':50, 's2':60,'s3':70}


In [21]:
s1 = pd.Series(d1)
s2 = pd.Series(d2)

In [22]:
s1.head()

s1    10
s2    20
s3    30
dtype: int64

In [24]:
df = pd.DataFrame({'Student1':s1,'Student2':s2})
df

Student1  Student2
s1        10        50
s2        20        60
s3        30        70

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, s1 to s3
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Student1  3 non-null      int64
 1   Student2  3 non-null      int64
dtypes: int64(2)
memory usage: 72.0+ bytes


In [26]:
#Preprocessing


In [27]:
import pandas as pd

In [49]:
df = pd.read_csv('./ml_dataset/purchase.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      NaN       Yes

In [29]:
df.shape

(10, 4)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [33]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [34]:
df.dropna()

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [35]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [36]:
df2 = df.dropna()
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    8 non-null      object 
 1   Age        8 non-null      float64
 2   Salary     8 non-null      float64
 3   Purchased  8 non-null      object 
dtypes: float64(2), object(2)
memory usage: 320.0+ bytes


In [37]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [38]:
#fillna
df.fillna(0)

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      0.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   0.0  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [39]:
d1 = {'Age':100,'Salary':200}
df.fillna(value=d1)

Country    Age   Salary Purchased
0   France   44.0  72000.0       No 
1    Spain   27.0  48000.0       Yes
2  Germany   30.0  54000.0       No 
3    Spain   38.0  61000.0       No 
4  Germany   40.0    200.0       Yes
5   France   35.0  58000.0       Yes
6    Spain  100.0  52000.0       No 
7   France   48.0  79000.0       Yes
8  Germany   50.0  83000.0       No 
9   France   37.0  67000.0       Yes

In [51]:
d1 = {'Age':df.Age.mean(),'Salary':df['Salary'].mean()}
df.fillna(value=d1)

Country        Age        Salary Purchased
0   France  44.000000  72000.000000       No 
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000       No 
3    Spain  38.000000  61000.000000       No 
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000       No 
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000       No 
9   France  37.000000  67000.000000       Yes

In [41]:
#df2 = df
#df2

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [45]:
#df2['Age'][7] = None

C:\Users\sarat\AppData\Local\Temp\ipykernel_13140\352302893.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Age'][7] = None


In [46]:
#df2

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0       No 
7   France   NaN  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [50]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [48]:
#d1 = {'Age':100,'Salary':200}
#df.fillna(value=d1)

Country    Age   Salary Purchased
0   France   44.0  72000.0       No 
1    Spain   27.0  48000.0       Yes
2  Germany   30.0  54000.0       No 
3    Spain   38.0  61000.0       No 
4  Germany   40.0    200.0       Yes
5   France   35.0  58000.0       Yes
6    Spain  100.0  52000.0       No 
7   France  100.0  79000.0       Yes
8  Germany   50.0  83000.0       No 
9   France   37.0  67000.0       Yes

In [52]:
#ffill, bfill
df.ffill()

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  35.0  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [53]:
df.bfill()

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0  58000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  48.0  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [54]:
#Imputer
import numpy as np
from sklearn.impute import SimpleImputer

In [55]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [56]:
imputer.fit(df[['Age','Salary']])

SimpleImputer()

In [57]:
imputer.transform(df[['Age','Salary']])

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [58]:
df[['Age','Salary']] = imputer.fit_transform(df[['Age','Salary']])

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes